# Generated by Django 3.1.7 on 2021-05-22 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='tag',
            field=models.CharField(blank=True, choices=[('Low priority', 'Low priority'), ('High priority', 'High priority'), ('Medium priority', 'Medium priority')], max_length=20, null=True),
        ),
    ]
