# Generated by Django 3.1.7 on 2021-04-01 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_oauth_token', models.TextField(max_length=200, null=True)),
                ('twitter_oauth_token_secret', models.TextField(max_length=200, null=True)),
                ('twitter_user_id', models.TextField(max_length=200, null=True)),
                ('twitter_name', models.TextField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
