language: python
python:
  - "3.6"
git:
  depth: 2

branches:
  only:
  - master
  - develop
  - dockerize

check-tests: &CHECK_TESTS
  
  install:
    - pip install -r requirements.txt

  script:
    - python manage.py test   

stage-deploy: &STAGE_DEPLOY

  script:
    - echo "haha"  


jobs:
  include:
    - stage: tests
    - <<: *CHECK_TESTS
    name: "checking tests"
    if: branch IN (master, develop, dockerize)
    - stage: deploy
    - <<: *STAGE_DEPLOY
    name: "deploy"
    if: type=push AND branch IN (master, develop, dockerize)
     


stages:
  - tests