language: python
python:
  - "3.6"


branches:
  only:
  - master
  - develop
  - dockerize

check-tests: &CHECK_TESTS
  
  install:
    - pip install -r requirements.txt

  script:
    - python manage.py test   


jobs:
  include:
    - <<: *CHECK_TESTS
      name: "checking tests"
      if: branch IN (master, develop, dockerize)