language: python
python:
  - "3.6"
git:
  depth: 2

branches:
  only:
  - master
  - develop
  - dockerize

check-tests: &CHECK_TESTS
  
  install:
    - pip install -r requirements.txt

  script:
    - python manage.py test   


stage-deploy: &STAGE_DEPLOY

  script:
    - echo "haha"  


jobs:
  include:
    - stage: tests
      <<: *CHECK_TESTS

    - stage: deploy
      <<: *STAGE_DEPLOY
     


stages:
  - name: Tests
    if: branch IN (master, develop, dockerize)

  - name: Deploy
    if: type=push AND branch IN (master, develop, dockerize)