version: "3"
   
services:
  postgres:
    image: postgres
    container_name: swan-alpha_postgares
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose: 
      - "5432"
    env_file:
      - pg.env
    networks: 
      - swan-release

  swan:
    image: "${SWAN_IMAGE}"
    build: .
    hostname: swan
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    restart: on-failure
    env_file: 
      - swan.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks: 
      - swan-release

networks: 
  swan-release: