version: "3"
   
services:
  postgres:
    image: postgres
    container_name: swan-stage_postgares
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose: 
      - "5432"
    env_file:
      - pg.env
    networks: 
      - swan-stage

  pg-admin:
    image: dpage/pgadmin4
    container_name: swan-stage_pgadmin
    hostname: pgadmin4
    ports:
      - "10333:80"
    env_file: 
      - pgadmin.env
    depends_on:
      - postgres
    networks: 
      - swan-stage

  swan:
    image: swan
    build: .
    hostname: swan
    command: python manage.py runserver 0.0.0.0:9090
    volumes:
      - .:/code
    restart: on-failure
    env_file: 
      - swan.env
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks: 
      - swan-stage

networks: 
  swan-stage: