openapi: 3.0.1
info:
  title: Swan-App
  description: Swan team
  version: '0.2'
servers:
  - url: 'https://api.stage.swan-app.ir'
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT    
  responses:
    '403':
          description: Auth failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationFailed"
              examples:
                '0':
                  value: '{ "detail": "Authentication credentials were not provided." }'
  schemas:
    AuthenticationFailed:
      type: object
      properties:
        detail:
          type: string
    Message:
      type: object
      properties:
        message:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string
