openapi: 3.0.1
info:
  title: Swan-App
  description: Swan team
  version: '0.2'
servers:
  - url: 'https://api.stage.swan-app.ir'
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT    
  responses:
    '403':
          description: Auth failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationFailed"
              examples:
                '0':
                  value: '{ "detail": "Authentication credentials were not provided." }'
  schemas:
    AuthenticationFailed:
      type: object
      properties:
        detail:
          type: string
    Message:
      type: object
      properties:
        message:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string
    User:
      type: "object"
      properties:
        email:
          type: "string"
          format: "email"
        first_name:
          type: "string"
        last_name:
          type: "string"
        profile_picture:
          type: "string"
          format: "byte"
        last_login:
          type: "string"
          format: "date-time"
      xml:
        name: "User"


paths:
  /api/v1/users/signup/:
    post:
      description: Sign up new user
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                email:
                  type: string
                confirm_password:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "email" : "example@gmail.com",
                      "password" : "*****",
                      "confirm_password" : "*****"
                  }
      responses:
        '200':
          description: Successful creation of user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
              examples:
                '0':
                  value: '{"message":"Successful. Mail sent to user."}'
        '400':
          description: Register existing user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
              examples:
                '0':
                  value: '{"message":"This user already exists"}'
      servers:
        - url: 'https://api.stage.swan-app.ir'
    servers:
      - url: 'https://api.stage.swan-app.ir'
  /api/v1/users/profile/update/:
    put:
      security:
        - bearerAuth: []
      description: update users profile
      tags:
        - Users
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                profile_picture:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful creation of user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: "#/components/schemas/User"
              examples:
                '0':
                  value: '{
                            "user": {
                                "email": "example@gmail.com",
                                "first_name": "string",
                                "last_name": "string",
                                "profile_picture": "string",
                                "last_login": "2021-05-20T09:04:41.352Z"
                            }
                        }'
        '400':
          description: Missing parameters.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                '0':
                  value: '{
                              "error": "First name not submitted."
                          }'
                '1':
                  value: '{
                              "error": "Last name not submitted."
                          }'
        '403':
          $ref: "#/components/responses/403"
      servers:
        - url: 'https://api.stage.swan-app.ir'
    servers:
      - url: 'https://api.stage.swan-app.ir'
  /api/v1/users/login/:
    post:
      security: []
      description: Login
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                email:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "email" : "example@gmail.com",
                      "password" : "*****"
                  }
      responses:
        '200':
          description: Successful login.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
              examples:
                '0':
                  value: '{
                            "token": "TOKEN",
                            "user": {
                                "email": "example@gmail.com",
                                "first_name": "string",
                                "last_name": "string",
                                "profile_picture": "string",
                                "last_login": "2021-05-20T09:04:41.352Z"
                            }
                          }'
        '403':
          description: Not verified email.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
              examples:
                '0':
                  value: '{
                              "message": "User not verified. Mail sent to email."
                          }'
        '401':
          description: Wrong credentials.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
              examples:
                '0':
                  value: '{
                              "message": "Wrong user name password"
                          }'
      servers:
        - url: 'https://api.stage.swan-app.ir'
    servers:
      - url: 'https://api.stage.swan-app.ir'
  /api/v1/users/profile/{mail}:
    get:
      parameters:
        - in: path
          name: mail   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The user email
      security: 
        - bearerAuth: []
      description: View profile details.
      tags:
        - Users
      responses:
        '200':
          description: Successfully found data.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              examples:
                '0':
                  value: '{
                              "email": "example@gmail.com",
                              "first_name": "string",
                              "last_name": "string",
                              "profile_picture": "string",
                              "last_login": "2021-05-20T09:04:41.352Z"
                          }'
        '403': 
          $ref: "#/components/responses/403" #Authentication failed
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
              examples:
                '0':
                  value: '{"message": "User not found"}'
      servers:
        - url: 'https://api.stage.swan-app.ir'
    servers:
      - url: 'https://api.stage.swan-app.ir'




