version: "3"
   
services:
  postgres:
    image: postgres
    container_name: swan-stage_postgares
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose: 
      - "5432"
    env_file:
      - pg.env
    networks: 
      - swan-stage
      
  swan:
    image: "${SWAN_IMAGE}"
    build: .
    hostname: swan
    command: python manage.py runserver 0.0.0.0:9090
    volumes:
      - .:/code
    restart: on-failure
    env_file: 
      - swan.env
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks: 
      - swan-stage

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "10334:8080"
    volumes:
      - type: bind
        source: ./openapi.json
        target: /home/openapi.json
    environment:
      SWAGGER_JSON: /home/openapi.json
    networks:
      - swan-stage

  minio:
    image: minio/minio
    container_name: "stage-minio"
    hostname: stage-minio
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - ./minio-data:/data
    env_file: 
      - minio.env
    networks: 
      - swan-stage

  nginx:
    image: nginx:stable-alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "15033:80"
    networks: 
      - swan-stage
  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    hostname: stage-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - swan-stage
    env_file:
      - rabbitmq.env
  postfix:
    image: instrumentisto/postfix
    container_name: 'swan-stage_postfix'
    hostname: stage-postfix
    ports:
      - 25:25
    volumes:
      - ./postfix_main.cf:/etc/postfix/main.cf
    networks:
      - swan-stage
networks: 
  swan-stage: