version: "3"
   
services:
  postgres:
    image: postgres
    container_name: swan-stage_postgares
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose: 
      - "5432"
    env_file:
      - pg.env
    networks: 
      - swan-stage

  pg-admin:
    image: dpage/pgadmin4
    container_name: swan-stage_pgadmin
    hostname: pgadmin4
    ports:
      - "10333:80"
    env_file: 
      - pgadmin.env
    depends_on:
      - postgres
    networks: 
      - swan-stage

  swan:
    image: "${SWAN_IMAGE}"
    build: .
    hostname: swan
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    restart: on-failure
    env_file: 
      - swan.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks: 
      - swan-stage

  prometheus:
    image: prom/prometheus:v2.25.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 10334:9090
    networks: 
      - swan-stage

  grafana:
    image: grafana/grafana:7.5.2
    ports:
      - 10335:3000
    networks: 
      - swan-stage

networks: 
  swan-stage: