version: "3"
   
services:
  postgres:
    image: postgres
    container_name: swan-stage_postgares
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose: 
      - "5432"
    env_file:
      - pg.env
    networks: 
      - swan

  pg-admin:
    image: dpage/pgadmin4
    container_name: swan-stage_pgadmin
    hostname: pgadmin4
    ports:
      - "9090:80"
    env_file: 
      - pgadmin.env
    depends_on:
      - postgres
    networks: 
      - swan

  swan:
    image: "${SWAN_IMAGE}"
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    restart: on-failure
    env_file: 
      - swan.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks: 
      - swan

networks: 
  swan: