# Generated by Django 3.1.7 on 2021-04-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.FileField(null=True, upload_to=post.models.get_user_directory)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('caption', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('multimedia', models.ManyToManyField(blank=True, related_name='Post', to='post.Media')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
