# Generated by Django 3.1.7 on 2021-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Ads', 'Ads'), ('Branding', 'Branding'), ('News', 'News'), ('Quote', 'Quote'), ('Celebration', 'Celebration')], max_length=20, null=True),
        ),
    ]
