# Generated by Django 3.1.7 on 2021-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('Ads', 'Ads'), ('Branding', 'Branding'), ('Celebration', 'Celebration'), ('News', 'News'), ('Quote', 'Quote'), ('Sales', 'Sales')], max_length=20, null=True),
        ),
    ]
