# Generated by Django 3.1.7 on 2021-05-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_published_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
