# Generated by Django 3.1.7 on 2021-05-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210429_1603'),
        ('post', '0003_auto_20210503_1357'),
    ]

    operations = [
    ]
