# Generated by Django 3.1.7 on 2021-05-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0002_remove_mediastorage_title'),
        ('post', '0004_merge_20210503_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='multimedia',
            field=models.ManyToManyField(blank=True, related_name='Post', to='filestorage.MediaStorage'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, choices=[('Ads', 'Ads'), ('Branding', 'Branding'), ('Celebration', 'Celebration'), ('News', 'News'), ('Quote', 'Quote'), ('Sales', 'Sales')], max_length=20, null=True),
        ),
    ]
