# Generated by Django 3.1.7 on 2021-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210402_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
