# Generated by Django 3.1.7 on 2021-05-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210521_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Drafts', 'Drafts'), ('Published', 'Published'), ('Schedule', 'Schedule')], default='Draft', max_length=20, null=True),
        ),
    ]
