# Generated by Django 3.1.7 on 2021-04-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210410_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='Draft', max_length=20, null=True),
        ),
    ]
