# Generated by Django 3.1.7 on 2021-04-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20210410_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
