# Generated by Django 3.1.7 on 2021-04-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210319_1438'),
        ('post', '0009_auto_20210410_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_team', to='team.team'),
        ),
    ]
