# Generated by Django 3.1.7 on 2021-04-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210410_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Dr', 'Drafts'), ('Pu', 'Published')], default='Draft', max_length=20, null=True),
        ),
    ]
