# Generated by Django 3.1.7 on 2021-06-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('body_text', models.CharField(blank=True, max_length=700)),
                ('subject', models.CharField(blank=True, max_length=280)),
                ('reciviers', models.TextField(max_length=1000)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Send', 'Send'), ('Schedule', 'Schedule')], default='Draft', max_length=20, null=True)),
                ('template_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_team', to='team.team')),
            ],
        ),
    ]
