# Generated by Django 3.1.7 on 2021-05-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=60, null=True)),
                ('body_text', models.CharField(blank=True, max_length=700)),
                ('subject', models.CharField(max_length=280, null=True)),
                ('recivier', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('snder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_email', to='team.team')),
            ],
        ),
    ]
