# Generated by Django 3.1.7 on 2021-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
