# Generated by Django 3.1.7 on 2021-05-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210531_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='snder',
            new_name='sender',
        ),
    ]
