# Generated by Django 3.1.7 on 2021-03-17 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('logo', models.ImageField(null=True, upload_to=team.models.get_teamlogo_directory)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
