# Generated by Django 3.1.7 on 2021-03-18 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_auto_20210317_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pending_users',
            field=models.ManyToManyField(related_name='pending_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
