# Generated by Django 3.1.7 on 2021-05-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediastorage',
            name='title',
        ),
    ]
